# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.312
      - image: appium/appium-emulator:1.1-arsenal
      - image: selenium/standalone-chrome:4.1.1-20211217

    steps:
      - checkout:
          name: checkout code
      - run: gradle test

